---
- name: DT0283 健康診断ジョブ
  hosts: DT0283
  gather_facts: yes

  tasks:
    - name: PCの基本情報を画面に出力
      ansible.builtin.debug:
        msg:
          - "================ [ DT0283 端末情報 ] ================"
          - "ホスト名      : {{ ansible_hostname }}"
          - "OSバージョン  : {{ ansible_os_name }}"
          - "総メモリ容量  : {{ (ansible_memtotal_mb / 1024) | round(2) }} GB"

    - name: Cドライブの空き容量を出力
      ansible.builtin.debug:
        msg:
          - "================ [ ディスク残量 ] ================"
          - "ドライブ名  : {{ item.mount }}"
          - "全容量      : {{ (item.size_total / 1024 / 1024 / 1024) | round(2) }} GB"
          - "空き容量    : {{ (item.size_free / 1024 / 1024 / 1024) | round(2) }} GB"
      loop: "{{ ansible_mounts }}"
      when: item.mount == 'C:'
